import {
  // Базові іконки
  ShoppingBag,
  Utensils,
  Coffee,
  Car,
  Fuel,
  Flame,
  Shirt,
  HeartPulse,
  Lightbulb,
  Briefcase,
  TrendingUp,
  HelpCircle,
  // Нові іконки
  HeartHandshake,
  Gift,
  Laptop,
  Cloud,
  Wifi,
  GraduationCap,
  Key,
  Home,
  Wrench,
  Sparkles,
  Pill,
  Stethoscope,
  Dumbbell,
  Plane,
  Ticket,
  Wine,
  Palette,
  Landmark,
  Coins,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, any> = {
  // Поточні категорії
  Продукти: ShoppingBag,
  "Кафе та Ресторани": Utensils,
  Кава: Coffee,
  "Транспорт/Таксі": Car,
  Авто: Fuel,
  Підписки: Flame,
  Одяг: Shirt,
  "Здоров'я": HeartPulse,
  Комунальні: Lightbulb,
  "Зарплата/ФОП": Briefcase,
  Інвестиції: TrendingUp,
  Інше: HelpCircle,

  // 20 нових категорій
  Донати: HeartHandshake,
  Подарунки: Gift,
  "Техніка та гаджети": Laptop,
  "Софт та сервери": Cloud,
  "Зв'язок та інтернет": Wifi,
  "Освіта та книги": GraduationCap,
  "Оренда житла": Key,
  "Дім та затишок": Home,
  "Ремонт та сервіс": Wrench,
  "Догляд та гігієна": Sparkles,
  "Аптека та вітаміни": Pill,
  "Медицина та чекапи": Stethoscope,
  "Спорт та тренування": Dumbbell,
  "Подорожі та готелі": Plane,
  "Розваги та події": Ticket,
  "Бари та дегустації": Wine,
  "Хобі та відпочинок": Palette,
  "Податки та комісії": Landmark,
  "Кешбек та бонуси": Coins,
  "Дивіденди та купони": TrendingUp,
};

export const CATEGORY_COLORS: Record<string, string> = {
  // Поточні категорії
  Продукти: "#10B981",
  "Кафе та Ресторани": "#F59E0B",
  Кава: "#D97706",
  "Транспорт/Таксі": "#3B82F6",
  Авто: "#EF4444",
  Підписки: "#8B5CF6",
  Одяг: "#EC4899",
  "Здоров'я": "#14B8A6",
  Комунальні: "#6366F1",
  "Зарплата/ФОП": "#22C55E",
  Інвестиції: "#06B6D4",
  Інше: "#71717A",

  // 20 нових категорій
  Донати: "#F43F5E",
  Подарунки: "#FB7185",
  "Техніка та гаджети": "#38BDF8",
  "Софт та сервери": "#818CF8",
  "Зв'язок та інтернет": "#60A5FA",
  "Освіта та книги": "#A78BFA",
  "Оренда житла": "#F97316",
  "Дім та затишок": "#34D399",
  "Ремонт та сервіс": "#A3E635",
  "Догляд та гігієна": "#F472B6",
  "Аптека та вітаміни": "#2DD4BF",
  "Медицина та чекапи": "#0EA5E9",
  "Спорт та тренування": "#EAB308",
  "Подорожі та готелі": "#0284C7",
  "Розваги та події": "#C084FC",
  "Бари та дегустації": "#9333EA",
  "Хобі та відпочинок": "#F59E0B",
  "Податки та комісії": "#64748B",
  "Кешбек та бонуси": "#10B981",
  "Дивіденди та купони": "#14B8A6",
};
