-- ============================================================
-- Розширені фінансові можливості: Скарбнички, Інвестиції, 
-- Ліміти категорій та Спліт транзакцій
-- ============================================================

DO $$
BEGIN
  -- 1. Таблиця Скарбничок та Цілей заощаджень (savings_goals)
  CREATE TABLE IF NOT EXISTS public.savings_goals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    target_amount numeric NOT NULL,
    current_amount numeric NOT NULL DEFAULT 0,
    currency text NOT NULL DEFAULT 'UAH',
    target_date date,
    created_at timestamptz NOT NULL DEFAULT now()
  );
  RAISE NOTICE '✅ Таблиця savings_goals готова';

  -- 2. Таблиця Інвестиційного портфеля (investments)
  CREATE TABLE IF NOT EXISTS public.investments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_name text NOT NULL,
    asset_type text NOT NULL, -- 'bonds' (ОВДП), 'stocks' (ETF/Акції), 'crypto' (Криптовалюта), 'deposit' (Депозит), 'other'
    invested_amount numeric NOT NULL, -- Вкладена сума (Cost Basis)
    current_value numeric NOT NULL, -- Поточна ринкова вартість
    currency text NOT NULL DEFAULT 'UAH',
    yield_percent numeric, -- Очікувана річна дохідність (%)
    maturity_date date, -- Дата погашення (для облігацій або депозитів)
    notes text,
    created_at timestamptz NOT NULL DEFAULT now()
  );
  RAISE NOTICE '✅ Таблиця investments готова';

  -- 3. Таблиця Лімітів за категоріями (category_budgets)
  CREATE TABLE IF NOT EXISTS public.category_budgets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name text NOT NULL UNIQUE,
    monthly_limit numeric NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  );
  RAISE NOTICE '✅ Таблиця category_budgets готова';

  -- 4. Розширення таблиці transactions для сплітів та мультивалютності
  IF EXISTS (
    SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'transactions'
  ) THEN
    -- Батьківська транзакція для сплітів (parent_transaction_id)
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns 
      WHERE table_schema = 'public' AND table_name = 'transactions' AND column_name = 'parent_transaction_id'
    ) THEN
      ALTER TABLE public.transactions ADD COLUMN parent_transaction_id bigint REFERENCES public.transactions(id) ON DELETE CASCADE;
      RAISE NOTICE '✅ Додано колонку parent_transaction_id до transactions';
    END IF;

    -- Оригінальна сума у валюті операції
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns 
      WHERE table_schema = 'public' AND table_name = 'transactions' AND column_name = 'original_amount'
    ) THEN
      ALTER TABLE public.transactions ADD COLUMN original_amount numeric;
      RAISE NOTICE '✅ Додано колонку original_amount до transactions';
    END IF;

    -- Валюта операції
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns 
      WHERE table_schema = 'public' AND table_name = 'transactions' AND column_name = 'original_currency'
    ) THEN
      ALTER TABLE public.transactions ADD COLUMN original_currency text DEFAULT 'UAH';
      RAISE NOTICE '✅ Додано колонку original_currency до transactions';
    END IF;
  END IF;

  -- 5. Активація RLS для нових таблиць (Default-Deny для публічного анонімного ключа)
  ALTER TABLE public.savings_goals ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.investments ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.category_budgets ENABLE ROW LEVEL SECURITY;

  RAISE NOTICE '🔒 RLS активовано для всіх нових таблиць (доступ лише для service_role)';
END $$;
