-- ============================================================
-- Поведінкова психологія та усвідомлені покупки:
-- 1. Таблиця «Лист очікування / Анти-імпульс» (wishlist_items)
-- 2. Таблиця «Вартість одного використання» (cost_per_use_items)
-- ============================================================

DO $$
BEGIN
  -- 1. Таблиця Листа бажань з таймером охолодження (wishlist_items)
  CREATE TABLE IF NOT EXISTS public.wishlist_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    estimated_price numeric NOT NULL,
    currency text NOT NULL DEFAULT 'UAH',
    category_name text NOT NULL DEFAULT 'Інше',
    url text,
    notes text,
    cooling_days integer NOT NULL DEFAULT 14,
    cooling_end_date timestamptz NOT NULL,
    status text NOT NULL DEFAULT 'cooling', -- 'cooling', 'ready', 'purchased', 'saved'
    resolved_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
  );
  RAISE NOTICE '✅ Таблиця wishlist_items готова';

  -- 2. Таблиця відстеження вартості одного використання (cost_per_use_items)
  CREATE TABLE IF NOT EXISTS public.cost_per_use_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name text NOT NULL,
    category_name text NOT NULL DEFAULT 'Інше',
    purchase_price numeric NOT NULL,
    currency text NOT NULL DEFAULT 'UAH',
    purchase_date date NOT NULL DEFAULT CURRENT_DATE,
    total_uses integer NOT NULL DEFAULT 1,
    benchmark_cost_per_use numeric, -- Орієнтовна вартість зовнішнього сервісу/чашки (UAH)
    target_cost_per_use numeric, -- Бажана ціль вартості за використання
    notes text,
    last_used_at timestamptz DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now()
  );
  RAISE NOTICE '✅ Таблиця cost_per_use_items готова';

  -- 3. Активація Row Level Security (RLS) для нових таблиць
  ALTER TABLE public.wishlist_items ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.cost_per_use_items ENABLE ROW LEVEL SECURITY;

  RAISE NOTICE '🔒 RLS активовано для wishlist_items та cost_per_use_items';
END $$;
