-- ============================================================
-- Фінансовий Календар: Кастомні події та нагадування
-- ============================================================

DO $$
BEGIN
  CREATE TABLE IF NOT EXISTS public.financial_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    amount numeric,
    currency text NOT NULL DEFAULT 'UAH',
    event_date date NOT NULL,
    is_recurring boolean NOT NULL DEFAULT false,
    category text,
    event_type text NOT NULL DEFAULT 'reminder', -- 'expense' | 'income' | 'reminder'
    notify_days_before integer[] NOT NULL DEFAULT '{7,3,1}',
    is_completed boolean NOT NULL DEFAULT false,
    last_notified_at timestamptz,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now()
  );
  RAISE NOTICE '✅ Таблиця financial_events створена або вже існує';

  -- Індекси для швидкого пошуку за датою та активними нагадуваннями
  CREATE INDEX IF NOT EXISTS idx_financial_events_date ON public.financial_events (event_date);
  CREATE INDEX IF NOT EXISTS idx_financial_events_active ON public.financial_events (is_completed, event_date);

  -- Активація Row Level Security (RLS)
  ALTER TABLE public.financial_events ENABLE ROW LEVEL SECURITY;
  RAISE NOTICE '🔒 RLS активовано для financial_events';
END $$;
